//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SymetricMatrix : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SymetricMatrix(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SymetricMatrix obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SymetricMatrix() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cppdllPINVOKE.delete_SymetricMatrix(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SymetricMatrix(double c) : this(cppdllPINVOKE.new_SymetricMatrix__SWIG_0(c), true) {
  }

  public SymetricMatrix() : this(cppdllPINVOKE.new_SymetricMatrix__SWIG_1(), true) {
  }

  public SymetricMatrix(double m11, double m12, double m13, double m14, double m22, double m23, double m24, double m33, double m34, double m44) : this(cppdllPINVOKE.new_SymetricMatrix__SWIG_2(m11, m12, m13, m14, m22, m23, m24, m33, m34, m44), true) {
  }

  public SymetricMatrix(double a, double b, double c, double d) : this(cppdllPINVOKE.new_SymetricMatrix__SWIG_3(a, b, c, d), true) {
  }

  public double det(int a11, int a12, int a13, int a21, int a22, int a23, int a31, int a32, int a33) {
    double ret = cppdllPINVOKE.SymetricMatrix_det(swigCPtr, a11, a12, a13, a21, a22, a23, a31, a32, a33);
    return ret;
  }

  public SWIGTYPE_p_double m {
    set {
      cppdllPINVOKE.SymetricMatrix_m_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = cppdllPINVOKE.SymetricMatrix_m_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

}
