//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class cppdllPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="SWIGRegisterExceptionCallbacks_cppdll")]
    public static extern void SWIGRegisterExceptionCallbacks_cppdll(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_cppdll")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_cppdll(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_cppdll(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_cppdll(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(cppdllPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(cppdllPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="SWIGRegisterStringCallback_cppdll")]
    public static extern void SWIGRegisterStringCallback_cppdll(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_cppdll(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static cppdllPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Clear")]
  public static extern void IntVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Add")]
  public static extern void IntVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_size")]
  public static extern uint IntVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_capacity")]
  public static extern uint IntVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_reserve")]
  public static extern void IntVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_IntVector__SWIG_0")]
  public static extern global::System.IntPtr new_IntVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_IntVector__SWIG_1")]
  public static extern global::System.IntPtr new_IntVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_IntVector__SWIG_2")]
  public static extern global::System.IntPtr new_IntVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_getitemcopy")]
  public static extern int IntVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_getitem")]
  public static extern int IntVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_setitem")]
  public static extern void IntVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_AddRange")]
  public static extern void IntVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_GetRange")]
  public static extern global::System.IntPtr IntVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Insert")]
  public static extern void IntVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_InsertRange")]
  public static extern void IntVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_RemoveAt")]
  public static extern void IntVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_RemoveRange")]
  public static extern void IntVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Repeat")]
  public static extern global::System.IntPtr IntVector_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Reverse__SWIG_0")]
  public static extern void IntVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Reverse__SWIG_1")]
  public static extern void IntVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_SetRange")]
  public static extern void IntVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Contains")]
  public static extern bool IntVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_IndexOf")]
  public static extern int IntVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_LastIndexOf")]
  public static extern int IntVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_IntVector_Remove")]
  public static extern bool IntVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_IntVector")]
  public static extern void delete_IntVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Clear")]
  public static extern void DoubleVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Add")]
  public static extern void DoubleVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_size")]
  public static extern uint DoubleVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_capacity")]
  public static extern uint DoubleVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_reserve")]
  public static extern void DoubleVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_DoubleVector__SWIG_0")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_DoubleVector__SWIG_1")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_DoubleVector__SWIG_2")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_getitemcopy")]
  public static extern double DoubleVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_getitem")]
  public static extern double DoubleVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_setitem")]
  public static extern void DoubleVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_AddRange")]
  public static extern void DoubleVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_GetRange")]
  public static extern global::System.IntPtr DoubleVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Insert")]
  public static extern void DoubleVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_InsertRange")]
  public static extern void DoubleVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_RemoveAt")]
  public static extern void DoubleVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_RemoveRange")]
  public static extern void DoubleVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Repeat")]
  public static extern global::System.IntPtr DoubleVector_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Reverse__SWIG_0")]
  public static extern void DoubleVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Reverse__SWIG_1")]
  public static extern void DoubleVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_SetRange")]
  public static extern void DoubleVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Contains")]
  public static extern bool DoubleVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_IndexOf")]
  public static extern int DoubleVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_LastIndexOf")]
  public static extern int DoubleVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_DoubleVector_Remove")]
  public static extern bool DoubleVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_DoubleVector")]
  public static extern void delete_DoubleVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_x_set")]
  public static extern void vector3_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_x_get")]
  public static extern double vector3_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_y_set")]
  public static extern void vector3_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_y_get")]
  public static extern double vector3_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_z_set")]
  public static extern void vector3_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vector3_z_get")]
  public static extern double vector3_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_vector3")]
  public static extern global::System.IntPtr new_vector3();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_vector3")]
  public static extern void delete_vector3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_x_set")]
  public static extern void vec3f_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_x_get")]
  public static extern double vec3f_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_y_set")]
  public static extern void vec3f_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_y_get")]
  public static extern double vec3f_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_z_set")]
  public static extern void vec3f_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_z_get")]
  public static extern double vec3f_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_vec3f__SWIG_0")]
  public static extern global::System.IntPtr new_vec3f__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_vec3f__SWIG_1")]
  public static extern global::System.IntPtr new_vec3f__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_vec3f__SWIG_2")]
  public static extern global::System.IntPtr new_vec3f__SWIG_2(double jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_v3")]
  public static extern global::System.IntPtr vec3f_v3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_dot")]
  public static extern double vec3f_dot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_cross")]
  public static extern global::System.IntPtr vec3f_cross(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_angle")]
  public static extern double vec3f_angle(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_angle2")]
  public static extern double vec3f_angle2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_rot_x")]
  public static extern global::System.IntPtr vec3f_rot_x(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_rot_y")]
  public static extern global::System.IntPtr vec3f_rot_y(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_clamp")]
  public static extern void vec3f_clamp(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_rot_z")]
  public static extern global::System.IntPtr vec3f_rot_z(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_invert")]
  public static extern global::System.IntPtr vec3f_invert(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_frac")]
  public static extern global::System.IntPtr vec3f_frac(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_integer")]
  public static extern global::System.IntPtr vec3f_integer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_length")]
  public static extern double vec3f_length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_normalize__SWIG_0")]
  public static extern global::System.IntPtr vec3f_normalize__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_vec3f_normalize__SWIG_1")]
  public static extern global::System.IntPtr vec3f_normalize__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_vec3f")]
  public static extern void delete_vec3f(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_SymetricMatrix__SWIG_0")]
  public static extern global::System.IntPtr new_SymetricMatrix__SWIG_0(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_SymetricMatrix__SWIG_1")]
  public static extern global::System.IntPtr new_SymetricMatrix__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_SymetricMatrix__SWIG_2")]
  public static extern global::System.IntPtr new_SymetricMatrix__SWIG_2(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9, double jarg10);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_SymetricMatrix__SWIG_3")]
  public static extern global::System.IntPtr new_SymetricMatrix__SWIG_3(double jarg1, double jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_SymetricMatrix_det")]
  public static extern double SymetricMatrix_det(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, int jarg9, int jarg10);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_SymetricMatrix_m_set")]
  public static extern void SymetricMatrix_m_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_SymetricMatrix_m_get")]
  public static extern global::System.IntPtr SymetricMatrix_m_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_SymetricMatrix")]
  public static extern void delete_SymetricMatrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_v_set")]
  public static extern void Simplify_Triangle_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_v_get")]
  public static extern global::System.IntPtr Simplify_Triangle_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_err_set")]
  public static extern void Simplify_Triangle_err_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_err_get")]
  public static extern global::System.IntPtr Simplify_Triangle_err_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_deleted_set")]
  public static extern void Simplify_Triangle_deleted_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_deleted_get")]
  public static extern int Simplify_Triangle_deleted_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_dirty_set")]
  public static extern void Simplify_Triangle_dirty_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_dirty_get")]
  public static extern int Simplify_Triangle_dirty_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_n_set")]
  public static extern void Simplify_Triangle_n_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Triangle_n_get")]
  public static extern global::System.IntPtr Simplify_Triangle_n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_Simplify_Triangle")]
  public static extern global::System.IntPtr new_Simplify_Triangle();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_Simplify_Triangle")]
  public static extern void delete_Simplify_Triangle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_p_set")]
  public static extern void Simplify_Vertex_p_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_p_get")]
  public static extern global::System.IntPtr Simplify_Vertex_p_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_tstart_set")]
  public static extern void Simplify_Vertex_tstart_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_tstart_get")]
  public static extern int Simplify_Vertex_tstart_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_tcount_set")]
  public static extern void Simplify_Vertex_tcount_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_tcount_get")]
  public static extern int Simplify_Vertex_tcount_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_q_set")]
  public static extern void Simplify_Vertex_q_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_q_get")]
  public static extern global::System.IntPtr Simplify_Vertex_q_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_border_set")]
  public static extern void Simplify_Vertex_border_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Vertex_border_get")]
  public static extern int Simplify_Vertex_border_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_Simplify_Vertex")]
  public static extern global::System.IntPtr new_Simplify_Vertex();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_Simplify_Vertex")]
  public static extern void delete_Simplify_Vertex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Ref_tid_set")]
  public static extern void Simplify_Ref_tid_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Ref_tid_get")]
  public static extern int Simplify_Ref_tid_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Ref_tvertex_set")]
  public static extern void Simplify_Ref_tvertex_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_Ref_tvertex_get")]
  public static extern int Simplify_Ref_tvertex_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_Simplify_Ref")]
  public static extern global::System.IntPtr new_Simplify_Ref();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_Simplify_Ref")]
  public static extern void delete_Simplify_Ref(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_triangles_set")]
  public static extern void Simplify_triangles_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_triangles_get")]
  public static extern global::System.IntPtr Simplify_triangles_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_vertices_set")]
  public static extern void Simplify_vertices_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_vertices_get")]
  public static extern global::System.IntPtr Simplify_vertices_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_refs_set")]
  public static extern void Simplify_refs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_refs_get")]
  public static extern global::System.IntPtr Simplify_refs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_vertex_error")]
  public static extern double Simplify_vertex_error(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3, double jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_calculate_error")]
  public static extern double Simplify_calculate_error(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_flipped")]
  public static extern bool Simplify_flipped(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_update_triangles")]
  public static extern void Simplify_update_triangles(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_update_mesh")]
  public static extern void Simplify_update_mesh(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_compact_mesh")]
  public static extern void Simplify_compact_mesh(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_min")]
  public static extern double Simplify_min(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_simplify_mesh__SWIG_0")]
  public static extern void Simplify_simplify_mesh__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_simplify_mesh__SWIG_1")]
  public static extern void Simplify_simplify_mesh__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_simplify_mesh__SWIG_2")]
  public static extern void Simplify_simplify_mesh__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_simplify_mesh_lossless__SWIG_0")]
  public static extern void Simplify_simplify_mesh_lossless__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_simplify_mesh_lossless__SWIG_1")]
  public static extern void Simplify_simplify_mesh_lossless__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_write_obj")]
  public static extern void Simplify_write_obj(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_load_obj")]
  public static extern void Simplify_load_obj(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_AddVertex")]
  public static extern void Simplify_AddVertex(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_AddTriangle")]
  public static extern void Simplify_AddTriangle(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_vCount")]
  public static extern int Simplify_vCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_triCount")]
  public static extern int Simplify_triCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_GetVertex")]
  public static extern void Simplify_GetVertex(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_Simplify_GetTriangle")]
  public static extern void Simplify_GetTriangle(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_new_Simplify")]
  public static extern global::System.IntPtr new_Simplify();

  [global::System.Runtime.InteropServices.DllImport("cppdll", EntryPoint="CSharp_delete_Simplify")]
  public static extern void delete_Simplify(global::System.Runtime.InteropServices.HandleRef jarg1);
}
